trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.21'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean package'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/target'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Azure subscription 1(46019087-95dd-42fb-8b7c-5cda417d426d)'
        appType: 'webAppLinux'
        appName: 'cicd-webapp'
        deployToSlotOrASE: true
        resourceGroupName: 'cicd-rg'
        slotName: 'production'
        package: '$(Build.ArtifactStagingDirectory)/app.zip'
        runtimeStack: 'TOMCAT|10.0-java21'

