name: Build and deploy JAR app to Azure Web App - cicd-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Dev'
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: java-app
          path: java-app

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App (Dev)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cicd-webapp-dev'
          slot-name: 'Production'
          package: java-app/*.jar

  deploy-stage:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: 'Stage'
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: java-app
          path: java-app

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App (Stage)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cicd-webapp-stage'
          slot-name: 'Production'
          package: java-app/*.jar

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-stage
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: java-app
          path: java-app

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App (Prod)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cicd-webapp'
          slot-name: 'Production'
          package: java-app/*.jar
